version: '3.9'
services:
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    image: task-manager
    container_name: task-manager
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    volumes:
      - taskdb:/app/instance
    environment:
      - FLASK_APP=${FLASK_APP:-APP}
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - PORT=${PORT:-5000}
    env_file:
      - .env
    networks:
      - web

  prometheus:
    image: prom/prometheus
    container_name: tm_prometheus
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090
    networks:
      - web

  grafana:
    image: grafana/grafana
    container_name: tm_grafana
    user: "472:472"
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_USERS_ALLOW_SIGN_UP: 'false'
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - web

volumes:
  taskdb:

networks:
  web:
    name: web-network
